### ISSUE TITLE
#任务1 ：  Multi-Agent

### ISSUE THREAD

**Issue by samqin123** [PancrePal-xiaoyibao/PancrePal-xiaoyibao#13]
**等级**
[x]  铂金级    

**任务名称**
[x ] Multi-agent多代理构建测试：作为小胰宝2.0-3.0的核心能力，测试并发布，实现小胰宝智能体的上线！

**状态**
[ x] 待领取
[ ] 已领取

**现状**
现有1.0版本及升级版本中，完成了复杂工作流的应用，并很好的将小胰宝从单一医疗问题智能助手，变成了“综合能力智能助手”，提供治疗的同时，可以完成一般性生活问答。
<img width="1423" alt="image" src="https://github.com/PancrePal-xiaoyibao/PancrePal-xiaoyibao/assets/103937568/ec54c39b-783f-4547-8a2a-a8784c31f68a">

实际肿瘤患者治疗中，综合治疗是核心理念，即“ 医学规范治疗 - 心理支援 - 营养支持” 三位一体，提供综合信息，而不是单一提供收入，药物，治疗方案这些单纯的医学内容。

因此在患者的后续服务中，小胰宝智能体，至少应该包括三个角色：
1. 医疗助手：保持和现在小胰宝一致的角色，提供循证前提下的科学规范治疗的相关信息支持，包括疾病信息，病情说明，治疗指南，治疗药物说明，并发症管理（疼痛/梗阻/腹水/骨髓抑制等科学干预）；
2. 营养指南：围绕病人全程治疗的营养支持信息管理，包括营养体系，食物成分，菜谱推荐，相关特殊阶段/特殊场景的营养支持治疗内容如肠内营养支持等；
3. 心理支援：围绕病人5阶段的心理需求，提供病人/家属方案的时候，也关注其心理状态和诉求，基于互动和必要的引导，积极影响。

Multi-agents需要构建以上3个agent并实现基于综合治疗场景的有效服务。

**交付**
1. 不限于fastgpt，请使用熟悉的环境/产品，实现智能体构建（比如框架CREW-AI，或者AutoGen等）
2. 至少提供应用的api接口，便于各服务端的调用（比如各种llm前端如lobechat, openUI, COW等）

**备注**
* 框架请自选
* 建议独立仓库提供

**Comment by xycjscs** [comment]
参与

**Comment by samqin123** [comment]
没想好用那个框架，先打算用python试一下思路crew-ai，欢迎大家提供建议

**Comment by samqin123** [comment]
期待后续大神领取，主导任务，我也是参与，所以任务还是标记open

**Comment by samqin123** [comment]
<img width="1746" alt="image" src="https://github.com/PancrePal-xiaoyibao/PancrePal-xiaoyibao/assets/103937568/b76f2dcd-6c3e-49ee-84f5-1ad04004571f">
cozy.cn尝试了一下，确实很方便，对于不会代码的用户，非常友好，5分钟实现了营养，医疗和写手的多agent

**Comment by samqin123** [comment]
但是cozy的确有很多工作流组件的却是，比如条件，这方面fastgpt和dify都适配。

**Comment by samqin123** [comment]
fastgpt完成了multi-agent的落地，issue顺利关闭。

**Comment by WillemJiang** [comment]
> fastgpt完成了multi-agent的落地，issue顺利关闭。

我对这块还是比较感兴趣的，最近也在研究多Agent的实现， 可以协助构建 coze 或者 crew AI 的 Agent ， 不知道有什么具体的参与方式？
