### ISSUE TITLE
[bug] 官网、体验网站无法访问

### ISSUE THREAD

**Issue by TechQuery** [PancrePal-xiaoyibao/PancrePal-xiaoyibao#4]
@samqin123 @zhuangbiaowei 
- http://www.pancrepal.asia/
- https://aibot.samqin.asia/

![image](https://github.com/PancrePal-xiaoyibao/PancrePal-xiaoyibao/assets/19969570/ea285a92-1fcf-49b9-a213-0cbd92770751)

**Comment by zhuangbiaowei** [comment]
http://www.pancrepal.asia/

这个已经从README.md里删除了，目前的两个体验网站，都是可以访问的。

README-en.md里的网址确实有bug，已经修复。
